[package]
name = "echoserver"
version = "0.0.4"
authors = ["Greg Dallavalle <greg.dallavalle@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
panic = "abort"

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
clap = "2"